[package]
name = "wallet_electrum_example"
version = "0.2.0"
edition = "2021"

[dependencies]
bdk_wallet = { path = "../../crates/wallet", features = ["file_store"] }
bdk_electrum = { path = "../../crates/electrum" }
anyhow = "1"
